# Generated by Django 5.0.2 on 2024-04-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_str', models.TextField(blank=True)),
                ('question_img', models.ImageField(blank=True, upload_to='')),
                ('question_type1', models.CharField(choices=[('Katta sinflar', 'Katta sinflar'), ('Kichik sinflar', 'Kichik sinflar')], max_length=100)),
                ('question_subject', models.CharField(max_length=15)),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('class_lebal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_student', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
        ),
    ]
