# Generated by Django 5.0.2 on 2024-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='question_subject',
            field=models.CharField(choices=[('Dasturlash', 'Dasturlash'), ('Matematika', 'Matematika'), ('Fizika', 'Fizika')], max_length=15),
        ),
    ]
